import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CalendarDays, FileText, LogOut, Menu, Settings, Ticket, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/admin")({component:Admin});
type Counts={events:number;registrations:number;speakers:number;sessions:number};
function Admin(){const navigate=useNavigate();const[checking,setChecking]=useState(true);const[authorised,setAuthorised]=useState(false);const[counts,setCounts]=useState<Counts>({events:0,registrations:0,speakers:0,sessions:0});useEffect(()=>{void(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){void navigate({to:"/auth"});return;}const{data:role}=await supabase.from("user_roles").select("role").eq("user_id",session.user.id).eq("role","admin").maybeSingle();if(!role){setChecking(false);return;}setAuthorised(true);const keys=(Object.keys(counts) as (keyof Counts)[]);const results=await Promise.all(keys.map(k=>supabase.from(k).select("*",{count:"exact",head:true})));setCounts(Object.fromEntries(keys.map((k,i)=>[k,results[i].count??0])) as Counts);setChecking(false);})()},[]);async function logout(){await supabase.auth.signOut();void navigate({to:"/auth"});}if(checking)return <main className="flex min-h-screen items-center justify-center font-mono text-xs text-lime">CHECKING ACCESS…</main>;if(!authorised)return <main className="flex min-h-screen items-center justify-center p-6 text-center"><div><p className="eyebrow">ACCESS RESTRICTED</p><h1 className="mt-5 font-display text-6xl">NOT AUTHORISED.</h1><p className="mt-4 text-muted-foreground">This account does not have the administrator role.</p><Button onClick={logout} variant="outline" className="mt-7 rounded-full">Sign out</Button></div></main>;
const cards=[{key:"registrations",label:"Registrations",icon:Ticket},{key:"events",label:"Events",icon:CalendarDays},{key:"speakers",label:"Speakers",icon:Users},{key:"sessions",label:"Sessions",icon:FileText}] as const;return <main className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-border bg-surface p-6 lg:flex lg:flex-col"><Link to="/" className="font-display text-3xl">FINVERSE <span className="text-lime">’26</span></Link><p className="eyebrow mt-3">ADMINISTRATION</p><nav className="mt-14 space-y-2"><span className="flex items-center gap-3 rounded bg-lime px-4 py-3 text-sm text-primary-foreground"><Menu className="h-4 w-4"/> Overview</span>{cards.map(c=><span key={c.key} className="flex items-center gap-3 px-4 py-3 text-sm text-muted-foreground"><c.icon className="h-4 w-4"/>{c.label}</span>)}<span className="flex items-center gap-3 px-4 py-3 text-sm text-muted-foreground"><Settings className="h-4 w-4"/> Settings</span></nav><button onClick={logout} className="mt-auto flex items-center gap-3 px-4 text-sm text-muted-foreground hover:text-lime"><LogOut className="h-4 w-4"/> Sign out</button></aside><div className="lg:ml-64"><header className="flex h-20 items-center justify-between border-b border-border px-6 md:px-10"><div><p className="font-display text-3xl">Command centre</p><p className="font-mono text-[10px] text-muted-foreground">LIVE CONTENT OVERVIEW</p></div><Button onClick={logout} variant="ghost" size="icon" className="lg:hidden"><LogOut/></Button></header><section className="p-6 md:p-10"><span className="eyebrow">MARKET OVERVIEW</span><h1 className="mt-4 font-display text-5xl">Good to see you.</h1><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><article key={c.key} className="border border-border bg-surface p-6"><div className="flex items-center justify-between"><c.icon className="text-lime"/><span className="font-mono text-[10px] text-muted-foreground">TOTAL</span></div><p className="mt-10 font-display text-6xl">{counts[c.key]}</p><p className="mt-2 text-sm text-muted-foreground">{c.label}</p></article>)}</div><section className="mt-10 border border-border p-7"><p className="eyebrow">CONTENT STATUS</p><h2 className="mt-4 font-display text-3xl">Connected to FINVERSE Cloud</h2><p className="mt-3 max-w-xl text-sm text-muted-foreground">Published content is protected by row-level security. Management modules use the same verified administrator access.</p></section></section></div></main>}