import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/register")({ validateSearch: (s: Record<string, unknown>) => ({ event: typeof s.event === "string" ? s.event : undefined }), component: Register });
type EventRow = { id: string; title: string; slug: string; registration_open: boolean };
function Register(){ const search=Route.useSearch(); const navigate=useNavigate(); const [events,setEvents]=useState<EventRow[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{void supabase.from("events").select("id,title,slug,registration_open").order("display_order").then(({data})=>setEvents(data??[]));},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);const selected=events.find(x=>x.id===fd.get("event_id"));if(!selected){setError("Choose an event to continue.");setLoading(false);return;}const registrationId=`FIN26-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const {error:dbError}=await supabase.from("registrations").insert({registration_id:registrationId,event_id:selected.id,name:String(fd.get("name")),email:String(fd.get("email")).toLowerCase(),phone:String(fd.get("phone")),college:String(fd.get("college")),year_of_study:String(fd.get("year")),team_name:String(fd.get("team_name")||"")||null,team_members:[],consent:true});if(dbError){setError(dbError.message.includes("duplicate")?"This email is already registered for the selected event.":"Registration could not be completed. Please try again.");setLoading(false);return;}void navigate({to:"/registration-success",search:{id:registrationId,event:selected.title}});}
  return <main className="site-container pt-36 pb-28"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><span className="eyebrow">ENTER FINVERSE ’26</span><h1 className="mt-8 font-display text-6xl md:text-8xl">MAKE YOUR<br/><span className="text-lime">MOVE.</span></h1><p className="mt-7 max-w-md text-muted-foreground">Choose your battleground and submit your details. Event-specific rules will be shared when confirmed.</p></div><form onSubmit={submit} className="border border-border bg-surface p-6 md:p-10"><p className="eyebrow">PARTICIPANT DETAILS</p><div className="mt-8 grid gap-6 md:grid-cols-2"><Field label="Full name"><Input name="name" required minLength={2}/></Field><Field label="Email"><Input name="email" type="email" required/></Field><Field label="Phone"><Input name="phone" type="tel" required pattern="[0-9+ -]{8,15}"/></Field><Field label="College / institution"><Input name="college" required/></Field><Field label="Year of study"><Input name="year" required placeholder="e.g. Second year"/></Field><Field label="Team name (optional)"><Input name="team_name"/></Field><label className="md:col-span-2"><span className="mb-2 block font-mono text-[10px] uppercase tracking-widest">Select event</span><select name="event_id" defaultValue={events.find(e=>e.slug===search.event)?.id??""} required className="h-11 w-full rounded border border-input bg-background px-3 text-sm"><option value="" disabled>Choose an event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></div><label className="mt-7 flex gap-3 text-sm text-muted-foreground"><input type="checkbox" required className="accent-lime"/><span>I confirm these details are accurate and consent to their use for event registration.</span></label>{error&&<p role="alert" className="mt-5 text-sm text-red-400">{error}</p>}<Button disabled={loading} className="mt-8 h-12 w-full rounded-full">{loading?"Submitting…":"Submit registration"}<ArrowRight/></Button></form></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block font-mono text-[10px] uppercase tracking-widest">{label}</span>{children}</label>}